# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HaiDan Sign

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 2,8 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      env:
        HAIDAN_UID: ${{ secrets.HAIDAN_UID }}
        HAIDAN_PASS: ${{ secrets.HAIDAN_PASS }}
        HAIDAN_LOGIN: ${{ secrets.HAIDAN_LOGIN }}
        HAIDAN_PRIVACY: ${{ secrets.HAIDAN_PRIVACY }}
      run: |
        python main.py
